import AppOpener, keyboard, time

AppOpener.open("google chrome", output=False)
time.sleep(0.2)
keyboard.press_and_release("Tab")
time.sleep(0.2)
keyboard.press_and_release("Tab")
time.sleep(0.2)
keyboard.press_and_release("Tab")
time.sleep(0.2)
keyboard.press_and_release("Tab")
time.sleep(0.2)
keyboard.press_and_release("Tab")
time.sleep(0.2)
keyboard.press_and_release("Enter")

AppOpener.open("Visual Studio Code, Spotify, WhatsApp", output=False)
time.sleep(0.2)
keyboard.press_and_release("left windows + Left")
time.sleep(0.2)
keyboard.press_and_release("Esc")